### ISSUE TITLE
Write back-end functionality for '/projects' page

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#16]

**Comment by laravelartisan** [comment]
I have written a Repository Interface implemented by Repository class (abstract) containing the definitions of the methods declared inside the interface. The Repository Class is extended by the Project(model) Repository class having only one method (model) to return the desired Model.
The Project Controller uses the Project Repository instead of the Project Model to fetch data or do other things.
The Repository class can be extended by any other Model Repository to reduce writing same code again n again; to make a data abstraction layer between a model and a controller.
